package api

// This file is generated by generate.go.
// Don't directly modify this file.

type DataCenter struct {
	Id           int
	Location     string
	Abbreviation string
}

var Dallas = DataCenter{
	Id:           2,
	Location:     "Dallas, TX, USA",
	Abbreviation: "dallas",
}

var Fremont = DataCenter{
	Id:           3,
	Location:     "Fremont, CA, USA",
	Abbreviation: "fremont",
}

var Atlanta = DataCenter{
	Id:           4,
	Location:     "Atlanta, GA, USA",
	Abbreviation: "atlanta",
}

var Newark = DataCenter{
	Id:           6,
	Location:     "Newark, NJ, USA",
	Abbreviation: "newark",
}

var London = DataCenter{
	Id:           7,
	Location:     "London, England, UK",
	Abbreviation: "london",
}

var Tokyo = DataCenter{
	Id:           8,
	Location:     "Tokyo, JP",
	Abbreviation: "tokyo",
}

var Singapore = DataCenter{
	Id:           9,
	Location:     "Singapore, SG",
	Abbreviation: "singapore",
}

var DataCenters = map[string]DataCenter{
	"Dallas":    Dallas,
	"Fremont":   Fremont,
	"Atlanta":   Atlanta,
	"Newark":    Newark,
	"London":    London,
	"Tokyo":     Tokyo,
	"Singapore": Singapore,
}
