package api

// This file is generated by generate.go.
// Don't directly modify this file.

type Plan struct {
	Id             int
	Cores          int
	Price          float32
	Ram            int
	Xfer           int
	Label          string
	DiskSpace      int
	HourlyCost     float32
	AvailableNodes map[string]int
}

var Linode_1024 = Plan{
	Cores:      1,
	Price:      10,
	Ram:        1024,
	Xfer:       2000,
	Id:         1,
	Label:      "Linode 1024",
	DiskSpace:  24,
	HourlyCost: 0.015,
}

var Linode_2048 = Plan{
	Cores:      2,
	Price:      20,
	Ram:        2048,
	Xfer:       3000,
	Id:         2,
	Label:      "Linode 2048",
	DiskSpace:  48,
	HourlyCost: 0.03,
}

var Linode_4096 = Plan{
	Cores:      4,
	Price:      40,
	Ram:        4096,
	Xfer:       4000,
	Id:         4,
	Label:      "Linode 4096",
	DiskSpace:  96,
	HourlyCost: 0.06,
}

var Linode_8192 = Plan{
	Cores:      6,
	Price:      80,
	Ram:        8192,
	Xfer:       8000,
	Id:         6,
	Label:      "Linode 8192",
	DiskSpace:  192,
	HourlyCost: 0.12,
}

var Linode_16384 = Plan{
	Cores:      8,
	Price:      160,
	Ram:        16384,
	Xfer:       16000,
	Id:         7,
	Label:      "Linode 16384",
	DiskSpace:  384,
	HourlyCost: 0.24,
}

var Linode_32768 = Plan{
	Cores:      12,
	Price:      320,
	Ram:        32768,
	Xfer:       20000,
	Id:         8,
	Label:      "Linode 32768",
	DiskSpace:  768,
	HourlyCost: 0.48,
}

var Linode_49152 = Plan{
	Cores:      16,
	Price:      480,
	Ram:        49152,
	Xfer:       20000,
	Id:         9,
	Label:      "Linode 49152",
	DiskSpace:  1152,
	HourlyCost: 0.72,
}

var Linode_65536 = Plan{
	Cores:      20,
	Price:      640,
	Ram:        65536,
	Xfer:       20000,
	Id:         10,
	Label:      "Linode 65536",
	DiskSpace:  1536,
	HourlyCost: 0.96,
}

var Linode_98304 = Plan{
	Cores:      20,
	Price:      960,
	Ram:        98304,
	Xfer:       20000,
	Id:         12,
	Label:      "Linode 98304",
	DiskSpace:  1920,
	HourlyCost: 1.44,
}

var Plans = map[string]Plan{
	"Linode_1024":  Linode_1024,
	"Linode_2048":  Linode_2048,
	"Linode_4096":  Linode_4096,
	"Linode_8192":  Linode_8192,
	"Linode_16384": Linode_16384,
	"Linode_32768": Linode_32768,
	"Linode_49152": Linode_49152,
	"Linode_65536": Linode_65536,
	"Linode_98304": Linode_98304,
}
